# Generated by Django 4.2.4 on 2023-08-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAzs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('road_code', models.IntegerField(verbose_name='Код дороги')),
                ('geomtype', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип фигуры')),
                ('coordinates', models.TextField(blank=True, null=True, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'АЗС',
                'verbose_name_plural': 'АЗС',
                'db_table': 'tbl_azs',
            },
        ),
        migrations.CreateModel(
            name='TblRoads',
            fields=[
                ('road_code', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Код дороги')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование дороги')),
                ('length_km', models.FloatField(blank=True, null=True, verbose_name='Протяженность')),
                ('geomtype', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип фигуры')),
                ('coordinates', models.TextField(blank=True, null=True, verbose_name='Список координат')),
            ],
            options={
                'verbose_name': 'Дорога',
                'verbose_name_plural': 'Дороги',
                'db_table': 'tbl_roads',
            },
        ),
    ]
